version: '17.3.1'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.1-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost:8929'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '4433:443'
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '512m'
    networks:
      - gitlab-network

networks:
  gitlab-network:
   name: gitlab-network
   external: true
